ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone_number VARCHAR(30);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS status VARCHAR(24);

UPDATE users
SET status = 'ACTIVE'
WHERE status IS NULL;

ALTER TABLE users
    ALTER COLUMN status SET DEFAULT 'PENDING_APPROVAL';

ALTER TABLE users
    ALTER COLUMN status SET NOT NULL;
